[platformio]
default_envs = waveshare_esp32s3_lcd7

[env:waveshare_esp32s3_lcd7]
platform = espressif32@6.5.0
board = waveshare_esp32s3_n16r8
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 115200
upload_flags =
    --before
    default_reset
    --after
    hard_reset
board_build.arduino.memory_type = qio_opi
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
lib_deps =
    lovyan03/LovyanGFX@^1.2.7
