#include "event_logs_page_script.h"
#include <Arduino.h>

String get_event_logs_page_styles() {
    return R"rawliteral(
.event-log { display: flex; flex-direction: column; gap: 8px; }
.event-item { background: rgba(0,0,0,0.3); padding: 10px; border-radius: 6px; }
.event-meta { color: #aaa; font-size: 12px; }
.event-error { color: #ff6b35; }
)rawliteral";
}

String get_event_logs_page_script() {
    return R"rawliteral(
async function loadEvents() {
    const status = document.getElementById('eventStatus');
    const list = document.getElementById('eventList');
    status.textContent = 'Loading...';
    list.innerHTML = '';
    try {
        const res = await fetch('/api/get_event_logs?limit=100');
        const data = await res.json();
        if (!data.success) {
            status.textContent = data.error || 'Event logs unavailable';
            status.className = 'event-meta event-error';
            return;
        }
        status.textContent = data.event_count + ' events';
        status.className = 'event-meta';
        if (data.events && data.events.length) {
            data.events.forEach(evt => {
                const item = document.createElement('div');
                item.className = 'event-item';
                const msg = (evt.message !== undefined && evt.message !== null) ? evt.message : 'Event';
                const lvl = (evt.level !== undefined && evt.level !== null) ? evt.level : 'N/A';
                const ts = (evt.timestamp !== undefined && evt.timestamp !== null) ? evt.timestamp : 'N/A';
                item.innerHTML = '<div><strong>' + msg + '</strong></div>' +
                                 '<div class="event-meta">Level: ' + lvl + ' | Time: ' + ts + '</div>';
                list.appendChild(item);
            });
        } else if (data.event_count === 0) {
            status.textContent = '0 events';
            const emptyMsg = document.createElement('div');
            emptyMsg.style.cssText = 'text-align: center; padding: 40px 20px; color: #888; font-size: 16px;';
            emptyMsg.innerHTML = '<div style="font-size: 48px; margin-bottom: 20px;">📋</div>' +
                                 '<div>No events to display</div>' +
                                 '<div style="font-size: 12px; margin-top: 10px;">Event logs will appear here when generated by the system</div>';
            list.appendChild(emptyMsg);
        }
    } catch (e) {
        status.textContent = 'Failed to load events';
        status.className = 'event-meta event-error';
    }
}

window.addEventListener('load', () => {
    fetch('/api/event_logs/subscribe', {method: 'POST'});
    loadEvents();
    setInterval(loadEvents, 5000);
});

window.addEventListener('beforeunload', () => {
    if (navigator.sendBeacon) {
        const blob = new Blob(['{}'], {type: 'application/json'});
        navigator.sendBeacon('/api/event_logs/unsubscribe', blob);
    } else {
        fetch('/api/event_logs/unsubscribe', {method: 'POST', keepalive: true});
    }
});
)rawliteral";
}
