#include "event_logs_page.h"
#include "../common/page_generator.h"
#include "../common/nav_buttons.h"
#include "../utils/transmitter_manager.h"
#include <Arduino.h>

// Event logs page handler - uses receiver API to fetch logs
static esp_err_t event_logs_page_handler(httpd_req_t *req) {
    String content = "";
    content += "<style>";
    content += ".event-log { display: flex; flex-direction: column; gap: 8px; }";
    content += ".event-item { background: rgba(0,0,0,0.3); padding: 10px; border-radius: 6px; }";
    content += ".event-meta { color: #aaa; font-size: 12px; }";
    content += ".event-error { color: #ff6b35; }";
    content += "</style>";

    content += "<h3>Event Logs</h3>";
    content += "<div id='eventStatus' class='event-meta'>Loading...</div>";
    content += "<div id='eventList' class='event-log'></div>";
    content += "<script>";
    content += "async function loadEvents() {";
    content += "  const status = document.getElementById('eventStatus');";
    content += "  const list = document.getElementById('eventList');";
    content += "  status.textContent = 'Loading...';";
    content += "  list.innerHTML = '';";
    content += "  try {";
    content += "    const res = await fetch('/api/get_event_logs?limit=100');";
    content += "    const data = await res.json();";
    content += "    if (!data.success) {";
    content += "      status.textContent = data.error || 'Event logs unavailable';";
    content += "      status.className = 'event-meta event-error';";
    content += "      return;";
    content += "    }";
    content += "    status.textContent = data.event_count + ' events';";
    content += "    status.className = 'event-meta';";
    content += "    if (data.events && data.events.length) {";
    content += "      data.events.forEach(evt => {";
    content += "        const item = document.createElement('div');";
    content += "        item.className = 'event-item';";
    content += "        const msg = (evt.message !== undefined && evt.message !== null) ? evt.message : 'Event';";
    content += "        const lvl = (evt.level !== undefined && evt.level !== null) ? evt.level : 'N/A';";
    content += "        const ts = (evt.timestamp !== undefined && evt.timestamp !== null) ? evt.timestamp : 'N/A';";
    content += "        item.innerHTML = '<div><strong>' + msg + '</strong></div>' +";
    content += "                        '<div class=\'event-meta\'>Level: ' + lvl + ' | Time: ' + ts + '</div>';";
    content += "        list.appendChild(item);";
    content += "      });";
    content += "    } else if (data.event_count === 0) {";
    content += "      status.textContent = '0 events';";
    content += "      const emptyMsg = document.createElement('div');";
    content += "      emptyMsg.style.cssText = 'text-align: center; padding: 40px 20px; color: #888; font-size: 16px;';";
    content += "      emptyMsg.innerHTML = '<div style=\"font-size: 48px; margin-bottom: 20px;\">📋</div><div>No events to display</div><div style=\"font-size: 12px; margin-top: 10px;\">Event logs will appear here when generated by the system</div>';";
    content += "      list.appendChild(emptyMsg);";
    content += "    }";
    content += "  } catch (e) {";
    content += "    status.textContent = 'Failed to load events';";
    content += "    status.className = 'event-meta event-error';";
    content += "  }";
    content += "}";
    content += "window.addEventListener('load', () => {";
    content += "  fetch('/api/event_logs/subscribe', {method: 'POST'});";
    content += "  loadEvents();";
    content += "  setInterval(loadEvents, 5000);";
    content += "});";
    content += "window.addEventListener('beforeunload', () => {";
    content += "  if (navigator.sendBeacon) {";
    content += "    const blob = new Blob(['{}'], {type: 'application/json'});";
    content += "    navigator.sendBeacon('/api/event_logs/unsubscribe', blob);";
    content += "  } else {";
    content += "    fetch('/api/event_logs/unsubscribe', {method: 'POST', keepalive: true});";
    content += "  }";
    content += "});";
    content += "</script>";

    content += generate_nav_buttons();

    String page = renderPage("Event Logs", content);
    httpd_resp_set_type(req, "text/html");
    httpd_resp_send(req, page.c_str(), page.length());
    
    return ESP_OK;
}

// Register event logs page
esp_err_t register_event_logs_page(httpd_handle_t server) {
    httpd_uri_t events_uri = {
        .uri = "/events",
        .method = HTTP_GET,
        .handler = event_logs_page_handler,
        .user_ctx = NULL
    };
    return httpd_register_uri_handler(server, &events_uri);
}
